#!/usr/bin/env python3
"""
Example: Calculate power consumption for an AstraSim simulation.

This script demonstrates how to use the power model with:
  1. AstraSim compute log (timestamped execution stats)
  2. Network link-traffic CSV (with per-link bandwidth)
  3. Topology nodemap JSON (optional; enables topology-aware switch power)
  4. Power config JSON (hardware parameters and LPM modes)

Usage:
  python calculate_power.py \
    --compute /path/to/astrasim.log \
    --network /path/to/link_traffic.csv \
    --nodemap /path/to/nodemap.json \
    --config /path/to/power_config.json
"""

import argparse
import sys
import os
from pathlib import Path

# Import power model components
from compute_parser import parse_astrasim_log
from network_parser import parse_network_statistics_csv
from power_config import PowerConfig
from power_model import PowerModel, compare_all_modes


def main():
    parser = argparse.ArgumentParser(
        description="Calculate power/energy consumption for AstraSim simulations",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
EXAMPLE USAGE:

1. Single-mode analysis (Mode A = baseline):
   python calculate_power.py \\
     --compute results/astrasim.log \\
     --network results/link_traffic.csv \\
     --config a100_config.json \\
     --nodemap topology/nodemap.json

2. Compare all 4 modes (A, B, C, D) with default config:
   python calculate_power.py \\
     --compute results/astrasim.log \\
     --network results/link_traffic.csv \\
     --compare

3. Custom config with topology-aware switches:
   python calculate_power.py \\
     --compute results/astrasim.log \\
     --network results/link_traffic.csv \\
     --config my_custom_config.json \\
     --nodemap topology/nodemap.json \\
     --topology topology/ns3_topology.json

FILE REQUIREMENTS:

  compute log:
    - Format: spdlog structured output from AstraSim
    - Contains: sys[X], Wall time: N, GPU time: N, Comm time: N (in cycles @ 1 GHz)
    - Example: \"[2026-03-01 23:11:40.576] [workload] [statistics] sys=0, Wall time: 1234567\"

  link_traffic.csv:
    - Columns: Source, Destination, Total_Bytes, Bandwidth (BG/s) [optional]
    - Source/Destination: node IDs (h0, t1, a2, etc.)
    - Total_Bytes: bytes transmitted over the simulation
    - Bandwidth: link capacity in GB/s (if absent, uses default 450 GB/s)
    - Example row: 0,148,70258845696.00,1800.0

  nodemap.json (optional):
    - Generated by nodemap_parser.py (or write manually)
    - Contains: hosts list, switches_by_type (nvswitch/tor/aggregation/core)
    - Enables topology-aware switch power modeling with per-type costs

  power_config.json:
    - Hardware parameters (GPU, NVLink, NIC, fabric, switch power)
    - LPM mode flags (compute_lpm_enabled, comm_lpm_enabled)
    - switch_degrees: ports per switch for each type
    - Example in a100_config.json
        """)

    parser.add_argument('--compute', required=True,
                        help='Path to AstraSim log file')
    parser.add_argument('--network', required=True,
                        help='Path to link_traffic.csv (with optional Bandwidth column)')
    parser.add_argument('--config', default=None,
                        help='Path to power config JSON (uses default if not specified)')
    parser.add_argument('--nodemap', default=None,
                        help='Path to nodemap.json for topology-aware switch power')
    parser.add_argument('--topology', default=None,
                        help='Path to NS3 topology file (used with --nodemap for degree inference)')
    parser.add_argument('--mode', choices=['A', 'B', 'C', 'D'], default=None,
                        help='Analyze single mode (A/B/C/D); if not set, compares all 4 modes')
    parser.add_argument('--output', default=None,
                        help='Save detailed breakdown as JSON')

    args = parser.parse_args()

    # Validate input files
    for fpath in [args.compute, args.network]:
        if not os.path.exists(fpath):
            print(f"❌ Error: File not found: {fpath}")
            sys.exit(1)

    if args.config and not os.path.exists(args.config):
        print(f"❌ Error: Config file not found: {args.config}")
        sys.exit(1)

    print("\n" + "="*80)
    print("🔋 ASTRASIM POWER MODEL CALCULATOR")
    print("="*80)
    print(f"\n📂 INPUT FILES:")
    print(f"  Compute log:      {args.compute}")
    print(f"  Network CSV:      {args.network}")
    if args.nodemap:
        print(f"  Nodemap:          {args.nodemap}")
    if args.topology:
        print(f"  Topology:         {args.topology}")
    if args.config:
        print(f"  Config:           {args.config}")
    else:
        print(f"  Config:           (default: Mode D - Full LPM)")

    # Parse inputs
    print(f"\n⏳ Parsing input files...")
    compute_stats = parse_astrasim_log(args.compute)
    
    # Load base config for topology preprocessing (prefix/host_prefix are mode-independent)
    if args.config:
        base_config = PowerConfig.from_json(args.config, mode='A')
    else:
        base_config = PowerConfig.create_mode_a()
    
    network_stats = parse_network_statistics_csv(
        args.network,
        nodemap_file=args.nodemap,
        topology_file=args.topology,
        prefix_map=base_config.switch_type_prefixes,
        host_prefix=base_config.host_prefix,
    )

    # Run power analysis
    if args.mode:
        # Single mode
        print(f"\n⚙️ Computing power for Mode {args.mode}...")
        if args.config:
            config = PowerConfig.from_json(args.config, mode=args.mode)
        else:
            mode_map = {
                'A': PowerConfig.create_mode_a,
                'B': PowerConfig.create_mode_b,
                'C': PowerConfig.create_mode_c,
                'D': PowerConfig.create_mode_d,
            }
            config = mode_map[args.mode]()
        
        model = PowerModel(compute_stats, network_stats, config)
        model.print_summary()
        
        breakdown = model.get_complete_breakdown()
        if args.output:
            import json
            with open(args.output, 'w') as f:
                json.dump(breakdown, f, indent=2)
            print(f"✅ Detailed breakdown saved to: {args.output}")
    else:
        # All 4 modes
        print(f"\n⚙️ Computing power for all 4 modes (A, B, C, D)...")
        if args.config:
            results = {}
            for mode in ['A', 'B', 'C', 'D']:
                config = PowerConfig.from_json(args.config, mode=mode)
                results[mode] = PowerModel(compute_stats, network_stats, config)
        else:
            results = compare_all_modes(compute_stats, network_stats)
        
        # Print summaries
        for mode_name in ['A', 'B', 'C', 'D']:
            results[mode_name].print_summary()
        
        # Comparison table
        print("\n" + "="*100)
        print("📊 4-MODE COMPARISON SUMMARY")
        print("="*100)
        print(f"{'Mode':<6} {'Description':<35} {'Power (W)':<12} {'Energy (J)':<12} {'Samples/J':<12}")
        print("-"*100)
        
        for mode_name in ['A', 'B', 'C', 'D']:
            bd = results[mode_name].get_complete_breakdown()
            print(f"{mode_name:<6} {bd['mode']:<35} "
                  f"{bd['total_power_W']:<12.2f} {bd['total_energy_J']:<12.2f} "
                  f"{bd['samples_per_joule']:<12.4f}")
        
        # Efficiency improvements
        print(f"\n📈 EFFICIENCY IMPROVEMENTS vs MODE A (Baseline):")
        baseline_energy = results['A'].total_energy()
        baseline_spj = results['A'].samples_per_joule()
        
        for mode_name in ['B', 'C', 'D']:
            energy = results[mode_name].total_energy()
            spj = results[mode_name].samples_per_joule()
            energy_saving = ((baseline_energy - energy) / baseline_energy) * 100
            efficiency = ((spj - baseline_spj) / baseline_spj) * 100
            print(f"  Mode {mode_name}: {energy_saving:+.2f}% energy saving  |  "
                  f"{efficiency:+.2f}% efficiency gain")
        
        print("="*100 + "\n")
        
        if args.output:
            import json
            detailed = {
                mode: results[mode].get_complete_breakdown()
                for mode in ['A', 'B', 'C', 'D']
            }
            with open(args.output, 'w') as f:
                json.dump(detailed, f, indent=2)
            print(f"✅ Detailed results saved to: {args.output}")


if __name__ == '__main__':
    main()
