topology: [ Ring ]
npus_count: [ 16 ]
bandwidth: [ 200 ]  # GB/s
latency: [ 0.0 ]  # ns
packet_size: 15000
header_size: 48
topology_file: "/home/xavid/feina/astra-sim/upc/configuration/g2/topology.json"
