npus_count: [ 16 ]
bandwidth_unit: GB/s
packet_size: 1500
header_size: 44
#topology_file: /media/mohammad/extension/experiments/astra-sim/upc/create_topology_old/totp/FoldedClos_128.json
topology_file: /media/mohammad/extension/experiments/astra-sim/upc/create_topology_old/FoldedClos_16_Uniform.json
#topology_file: /media/mohammad/extension/experiments/astra-sim/upc/create_topology/FoldedClos.json