"""
SimulationRunner: Handle AstraSim simulation execution.

This module:
1. Generates configuration files using config_generator (ALWAYS)
2. Generates workloads using workload_generator
3. Runs AstraSim simulations
4. Parses results using output_parser
5. Handles errors and cleanup

Config files are ALWAYS generated by config_generator - never user-provided.
"""

import os
import sys
import shutil
import time
import threading
import glob
import signal
from typing import Dict, Optional, Any

# Add UPC to path using environment variable
sys.path.insert(0, os.environ['ASTRA_SIM_ROOT'] + '/upc')
from run_astrasim import run_astrasim, post_process_simulation

sys.path.insert(0, os.environ['ASTRA_SIM_ROOT'] + '/upc/Optimization')
from ..helper import workload_generator, output_parser, config_generator, config_parser
from .simulation_tracker import SimulationTracker
from .power_estimator import run_power_estimation


class SimulationRunner:
    """
    Manages AstraSim simulation execution.
    
    Responsibilities:
    - Generate configs using config_generator
    - Setup directories
    - Generate workloads
    - Run simulations
    - Parse results
    - Cleanup
    
    Example:
        runner = SimulationRunner(
            model_num=40,
            model_name="GPT_40B",
            num_npus=64
        )
        
        exec_time = runner.run_simulation(config_dict)
    """
    
    def __init__(
        self,
        model_num: int,
        model_name: str,
        network_name: str = "FoldedClos",
        net_sim_config: Dict[str, Any] = {"sim_type": "analytical_unaware"},
        base_dir: Optional[str] = os.environ['ASTRA_SIM_ROOT'] + "/upc",
        folder_prefix: str = "OPT",
        clean_on_init: bool = True,
        verbose: bool = False,
        output_dir: Optional[str] = None,
        network_log_dir: Optional[str] = None,
        tracker: Optional[SimulationTracker] = None
    ):
        """
        Initialize simulation runner.
        
        Config files are ALWAYS generated by config_generator.
        No config paths can be provided - they are automatically managed.
        
        Args:
            model_num: Model identifier (from workload_generator.Model)
            model_name: Human-readable model name
            num_npus: Number of NPUs
            network_name: Network topology (FoldedClos, Switch, Ring, etc.)
            net_sim_config: Network simulation configuration dictionary (e.g., {"sim_type": "g2"})
            base_dir: Base directory for AstraSim
            folder_prefix: Prefix for output folders
            clean_on_init: Whether to clean previous results on initialization
            verbose: Whether to print detailed messages
            output_dir: Custom output directory (default: {base_dir}/output/{folder_prefix}_{model_name}/{network_name})
            network_log_dir: Custom network log directory (default: {base_dir}/network_log/{folder_prefix}_{model_name}/{network_name})
            tracker: Optional SimulationTracker for early termination of slow simulations
        """
        self.model_num = model_num
        self.model_name = model_name
        self.num_npus = 0
        self.network_name = network_name
        self.net_sim_config = net_sim_config
        self.base_dir = base_dir if base_dir is not None else os.environ['ASTRA_SIM_ROOT'] + '/upc'
        self.verbose = verbose
        self.tracker = tracker
        
        # Folder names
        self.folder_name = f"{folder_prefix}_{model_name}"
        
        # Config paths will be generated per-run by config_generator
        self.system_config = None
        self.network_config = None
        self.memory_config = None
        
        # Setup directories (use custom or default)
        self.workload_dir = f"{base_dir}/workload/{self.folder_name}"
        self.output_dir = output_dir if output_dir is not None else f"{base_dir}/output/{self.folder_name}/{network_name}"
        self.network_log_dir = network_log_dir if network_log_dir is not None else f"{base_dir}/network_log/{self.folder_name}/{network_name}"
        
        # Clean and create directories
        if clean_on_init:
            self.clean_previous_results()
        self.setup_directories()
    
    def setup_directories(self):
        """Create required directories."""
        os.makedirs(self.workload_dir, exist_ok=True)
        os.makedirs(self.output_dir, exist_ok=True)
        os.makedirs(self.network_log_dir, exist_ok=True)
        
        if self.verbose:
            print(f"Created directories:")
            print(f"  Workload: {self.workload_dir}")
            print(f"  Output: {self.output_dir}")
            print(f"  Network logs: {self.network_log_dir}")
    
    def clean_previous_results(self):
        """Clean previous simulation results."""
        dirs_to_clean = [
            self.workload_dir,
            self.output_dir,
            self.network_log_dir
        ]
        
        for dir_path in dirs_to_clean:
            if os.path.exists(dir_path):
                if self.verbose:
                    print(f"Removing: {dir_path}")
                shutil.rmtree(dir_path)
    
    def run_simulation(self, config: Dict, return_paths: bool = True, suffix: Optional[str] = None):
        """
        Run simulation for a configuration.
        
        Configs are ALWAYS generated fresh using config_generator.
        
        Args:
            config: Configuration dictionary with dp, mp, sp, pp, sharded 
                   (and optionally net_*, sys_*, mem_* parameters)
            return_paths: If True, return (exec_time, file_paths, metadata) tuple
            suffix: Optional suffix for output files (for parallel execution to avoid conflicts)
        
        Returns:
            If return_paths=False: Execution time in seconds, or None if failed
            If return_paths=True: (exec_time, file_paths_dict, metadata_dict) tuple, or None if failed
        """
        # Extract values from config dictionary
        dp = config['dp']
        mp = config['mp']
        sp = config['sp']
        pp = config['pp']
        sharded = config['sharded']
        self.num_npus = config.get('npu_count', self.num_npus)
        
        # Generate unique suffix for parallel execution if requested and not provided
        if suffix is None:
            import time
            import os
            suffix = f"_pid{os.getpid()}_t{int(time.time() * 1000000)}"
        
        if self.verbose:
            print(f"  Running: dp={dp}, mp={mp}, sp={sp}, pp={pp}, sharded={sharded}")
        
        try:
            # 0. Generate config files (ALWAYS, using config_generator)
            self.system_config, self.network_config, self.memory_config = \
                config_generator.generate_all_configs(config, net_sim_config=self.net_sim_config)
            
            if self.verbose:
                print(f"    Generated configs:")
                print(f"      System: {self.system_config}")
                print(f"      Network: {self.network_config}")
                print(f"      Memory: {self.memory_config}")
            
            # 1. Generate workload
            success = workload_generator.generate_workload_with_env(
                config,
                workload_generator.Model(self.model_num),
                self.folder_name,
                suffix=suffix
            )
            
            if not success:
                if self.verbose:
                    print("    ⚠️  Workload generation failed")
                return None
            
            # 2. Find generated workload file
            config_name = f"{dp}_{mp}_{sp}_{pp}_{1 if sharded else 0}"
            workload_file = self._find_workload_file(config_name, suffix=suffix)
            
            if workload_file is None:
                if self.verbose:
                    print("    ⚠️  Workload file not found")
                return None
            
            # Prepare paths for any post-run handling (including failures)
            config_basename = os.path.basename(workload_file)
            file_paths = {
                'workload': workload_file,
                'output_pattern': os.path.join(self.output_dir, config_basename),
                'system_config': self.system_config,
                'network_config': self.network_config,
                'memory_config': self.memory_config,
            }

            # 3. Run simulation
            if self.verbose:
                print(f"    Running simulation: {workload_file}")
            
            sim_start_time = time.time()  # Track wall clock time
            result, was_killed = self._run_astrasim(workload_file, suffix=suffix, config=config)
            sim_walltime = time.time() - sim_start_time  # Actual wall clock duration
            
            if was_killed:
                # The tracker decided this simulation is too slow to be useful.
                # Do NOT read the partial log — that value is an underestimate of
                # the true full-run cost and would mislead the optimizer.
                # Return float('inf') as exec_time: a clear penalty sentinel.
                print(f"    [Tracker] Simulation killed — PENALTY exec_time=inf")
                if return_paths:
                    metadata = self._get_simulation_metadata()
                    metadata['was_killed'] = True
                    metadata['sim_walltime'] = sim_walltime
                    return float('inf'), False, file_paths, metadata
                else:
                    return float('inf'), False
            
            if result != "":
                if self.verbose:
                    print(f"    ⚠️  Simulation failed: {result}")
                if return_paths:
                    metadata = self._get_simulation_metadata()
                    metadata['was_killed'] = False
                    metadata['sim_failed'] = True
                    metadata['sim_walltime'] = sim_walltime
                    return None, None, file_paths, metadata
                return None
            
            # 4. Extract execution time
            if self.verbose:
                print(f"    Parsing output log...")
            exec_time, is_oom = self._output_log_parser(workload_file, suffix=suffix)
            
            if exec_time is None:
                if self.verbose:
                    print("    ⚠️  Could not extract execution time", result)
                if return_paths:
                    metadata = self._get_simulation_metadata()
                    metadata['was_killed'] = False
                    metadata['sim_failed'] = True
                    metadata['sim_walltime'] = sim_walltime
                    return None, is_oom, file_paths, metadata
                return None
            
            if self.verbose:
                print(f"    ✓ Execution time: {exec_time:.2f}s")
            
            # 5. Run power estimation when explicitly requested (estimate_power=1, Mode D)
            power_metrics = {}
            if self.net_sim_config.get('estimate_power') == 1 and not is_oom:
                power_metrics = run_power_estimation(
                    output_dir=self.output_dir,
                    network_config=self.network_config,
                    base_dir=self.base_dir,
                    workload_file=workload_file,
                    power_config_path=self.net_sim_config.get('power_config_path'),
                    verbose=self.verbose,
                )
            
            # 6. Return with file paths and metadata if requested
            if return_paths:
                # Collect metadata about the actual simulation configuration
                metadata = self._get_simulation_metadata()
                metadata['sim_walltime'] = sim_walltime
                metadata['was_killed'] = False
                metadata['sim_failed'] = False
                metadata.update(power_metrics)  # Merge power metrics (empty dict if not g2 or failed)
                
                return exec_time, is_oom, file_paths, metadata
            else:
                return exec_time, is_oom
            
        except Exception as e:
            if self.verbose:
                print(f"    ⚠️  Error in run_simulation: {e}")
            # Return appropriate None tuple based on return_paths flag
            if return_paths:
                return None, None, {}, {'sim_failed': True}
            else:
                return None, None
    
    def _get_simulation_metadata(self) -> Dict:
        """
        Get metadata about the simulation configuration.
        
        Returns:
            Dictionary with model, network, hardware, and simulation parameters
        """
        # Get model parameters
        din, dout, dmodel, dff, batch, micro_batch, seq, head, num_stacks = workload_generator.Model.get_model_params(
            workload_generator.Model(self.model_num)
        )
        
        metadata = {
            # Model information
            'model_name': self.model_name,
            'model_num': self.model_num,
            'vocab_size_in': din,
            'vocab_size_out': dout,
            'hidden_size': dmodel,
            'ffn_hidden_size': dff,
            'batch_size': batch[0] if isinstance(batch, list) else batch,
            'micro_batch': micro_batch,
            'sequence_length': seq,
            'num_attention_heads': head,
            'num_layers': num_stacks,
            
            # Infrastructure
            'num_npus': self.num_npus,
            'sim_type': self.net_sim_config.get('sim_type', 'analytical_unaware'),
        }
        
        # Parse configuration files and add all parameters
        # Convert relative paths to absolute paths
        system_path = self.system_config if os.path.isabs(self.system_config) else os.path.join(self.base_dir, self.system_config)
        network_path = self.network_config if os.path.isabs(self.network_config) else os.path.join(self.base_dir, self.network_config)
        memory_path = self.memory_config if os.path.isabs(self.memory_config) else os.path.join(self.base_dir, self.memory_config)
        
        config_params = config_parser.parse_all_configs(
            system_path,
            network_path,
            memory_path
        )
        metadata.update(config_params)
        
        return metadata
    
    def _find_workload_file(self, config_name: str, suffix: str = "") -> Optional[str]:
        """
        Find generated workload file.
        
        Args:
            config_name: Configuration name (e.g., "4_8_2_1_1")
        
        Returns:
            Path to workload file without .0.et extension, or None if not found
        """
        pattern = f"{self.workload_dir}/{config_name}.seq_*.batch_*{suffix}.0.et"
        matching_files = glob.glob(pattern)
        #print("matching_files:",matching_files)
        if matching_files:
            # Remove .0.et suffix
            return matching_files[0][:-5]
        
        return None
    
    def _run_astrasim(
        self,
        workload_path: str,
        suffix: Optional[str] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> tuple:
        """
        Run AstraSim simulation with optional early termination.
        
        Args:
            workload_path: Path to workload file
            suffix: Optional suffix for output files (for parallel execution)
        
        Returns:
            Tuple of (error_message, was_killed)
            - error_message: Empty string if successful, error message otherwise
            - was_killed: True if simulation was killed early, False otherwise
        """
        # Special handling for g2 backend
        if self.net_sim_config.get('sim_type', 'analytical_unaware') == "g2":
            g2_path = os.environ['ASTRA_SIM_ROOT'] + '/extern/network_backend/g2'
            if 'PYTHONPATH' in os.environ:
                os.environ['PYTHONPATH'] = f"{g2_path}:{os.environ['PYTHONPATH']}"
            else:
                os.environ['PYTHONPATH'] = g2_path
        
        # If no tracker, run simulation normally
        if self.tracker is None:
            error = run_astrasim(
                workload_path=workload_path,
                system=self.system_config,
                network=self.network_config,
                memory=self.memory_config,
                output_dir=self.output_dir,
                network_log=self.network_log_dir,
                sim_type=self.net_sim_config.get('sim_type', 'analytical_unaware'),
                #suffix=suffix
            )
            return error, False
        
        # Run with tracking for early termination
        workload_filename = workload_path.split('/')[-1]
        trace_file = f"{self.output_dir}/{workload_filename}_trace.csv"
        
        # Start simulation - returns immediately with PID
        process, pid, log_path, keep_trace = run_astrasim(
            workload_path=workload_path,
            system=self.system_config,
            network=self.network_config,
            memory=self.memory_config,
            output_dir=self.output_dir,
            network_log=self.network_log_dir,
            sim_type=self.net_sim_config.get('sim_type', 'analytical_unaware'),
            return_pid=True,
            #keep_trace=True  # Keep trace file for tracking
        )
        
        # Track result in a dict
        result = {'killed': False, 'finished': False}
        
        # Start thread to wait for simulation completion
        def wait_for_completion():
            process.wait()
            # Post-process after simulation completes successfully
            if process.returncode == 0:
                post_process_simulation(log_path, keep_trace)
            result['finished'] = True
        
        wait_thread = threading.Thread(target=wait_for_completion, daemon=True)
        wait_thread.start()
        
        # Monitor simulation progress
        check_interval = 5  # Check every 50ms
        while not result['finished']:
            time.sleep(check_interval)
            
            # Check if simulation should be killed based on issue ticks
            if self.tracker.should_kill_simulation(trace_file, config=config):
                if process.poll() is None:
                    # Process is still running — kill it
                    result['killed'] = True
                    try:
                        #print(f"\n    ⚡ Killing simulation process group (PID: {pid})")
                        # Kill process group using negative PID
                        os.killpg(os.getpgid(pid), signal.SIGKILL)  # Use SIGKILL to ensure termination
                        wait_thread.join(timeout=2)  # Wait for thread to finish
                    except ProcessLookupError:
                        pass  # Process already finished
                    except Exception as e:
                        if self.verbose:
                            print(f"       Warning: Could not kill process: {e}")
                    break
            # If should_kill returned True but process already finished: do nothing,
            # let the loop exit naturally via result['finished'] = True.
        
        error = "" if process.returncode == 0 else "Simulation failed"
        return error, result['killed']
    
    def _output_log_parser(self, workload_file: str, suffix: Optional[str] = None) -> Optional[tuple]:
        """
        Extract execution time from simulation log.
        
        Args:
            workload_file: Path to workload file (without extension)
            suffix: Optional suffix for output files (must match what was used in run)
        
        Returns:
            Tuple of (exec_time, is_oom), or None if extraction failed
        """
        # Get workload filename
        workload_filename = workload_file.split('/')[-1]
        
        # Construct log file path with suffix if provided
        log_file = f"{self.output_dir}/{workload_filename}"
        log_file += ".log"
        
        if not os.path.exists(log_file):
            if self.verbose:
                print(f"    ⚠️  Log file does not exist: {log_file}")
            return None, None
        
        # Extract time using output_parser
        exec_time, is_oom = output_parser.output_log_parser(log_file)
        
        return exec_time, is_oom
    
    def batch_run(self, configs: list) -> list:
        """
        Run simulations for multiple configurations.
        
        Args:
            configs: List of configuration tuples
        
        Returns:
            List of execution times (None for failed runs)
        """
        results = []
        
        for i, config in enumerate(configs):
            if self.verbose:
                print(f"[{i+1}/{len(configs)}] ", end="")
            
            exec_time, is_oom = self.run_simulation(config)
            results.append((exec_time, is_oom))
        
        return results
    
    def __repr__(self) -> str:
        """String representation."""
        return (f"SimulationRunner(model={self.model_name}, "
                f"npus={self.num_npus}, network={self.network_name})")
    
    def __str__(self) -> str:
        """Human-readable string."""
        return (f"SimulationRunner\n"
                f"  Model: {self.model_name} (#{self.model_num})\n"
                f"  NPUs: {self.num_npus}\n"
                f"  Network: {self.network_name}\n"
                f"  Sim type: {self.net_sim_config.get('sim_type', 'analytical_unaware')}\n"
                f"  Output: {self.output_dir}")
